### ISSUE TITLE
Crash on Debian Stretch

### ISSUE THREAD

**Issue by hbrown-usa** [activityworkshop/GpsPrune#11] opened 2017-04-23 11:48 UTC
This is a high resolution kml file of the Eiffel Tower 3D:
A number of people indicated it did work on Google Earth I think.
The site is:
https://productforums.google.com/forum/#!topic/gec-models-annotations/SG8KhbccCAU

I install the Debian Stretch Package
I download the compressed version, unzip it and tried to load the doc.kml file.
The top view and elevation profile of the Eiffel Tower shows.
However, if I adjust any of the controls within the application it seems to crash and the UI disappear.

The author of the file indicates it has a high number of entries.  I am wondering if the software has been tested for large data files such as this one.

The attachments are:
[doc.zip](https://github.com/activityworkshop/GpsPrune/files/949658/doc.zip)
This is a rezipped file of the unzipped kmz file.
[dockmz.zip](https://github.com/activityworkshop/GpsPrune/files/949659/dockmz.zip)
This is the zipped of the original file from the link above.  You can download it directly from the link above.

**Comment by activityworkshop** [comment] 2017-09-17 11:15
I've tested this again with Debian Stretch, and can't get it to crash.  It gets rather slow, so there's probably room for improvement there, but I can't reproduce your crash.  I'm using the standard java 1.8 here, I'm not sure what you've got.
I'm closing this for now as unreproducible.

**Closed by activityworkshop** 2017-09-17 11:15 UTC
