### ISSUE TITLE
Map text is tiny on MacBook Air with Retina screen

### ISSUE THREAD

**Issue by lenlo** [activityworkshop/GpsPrune#50] opened 2022-05-11 00:17 UTC
Also, the scale seems to be wrong in that 0.2 km under 21.1 is shown as 0.1 km under 21.2 for the same map distance.

GpsPrune 21.1 (note scale showing 0.2 km):
<img width="1303" alt="Screenshot - GpsPrune 21 1-0 2" src="https://user-images.githubusercontent.com/4592527/167744247-a2f9a19b-e020-405d-9295-581a4658f4e4.png">

GpsPrune 21.2 (note scale showing 0.1 km):
<img width="1303" alt="Screenshot - GpsPrune 21 2-0 1" src="https://user-images.githubusercontent.com/4592527/167744289-d1eb0197-f030-43ad-8085-80639e7641e1.png">

Zooming one one more level under 21.1 show this (note scale showing 0.1 km):
<img width="1303" alt="Screenshot - GpsPrune 21 1-0 1" src="https://user-images.githubusercontent.com/4592527/167744302-d52f531d-e56d-4807-af18-a179bcd345a6.png">

(Zooming one one more level under 21.2 produces "No maps available at this zoom level")

I'm assuming this is related to https://github.com/activityworkshop/GpsPrune/issues/16.

This is using a MacBook Air (M1, 2020) running macOS Monterey 12.3.1 (21E258) with openjdk 18.0.1 2022-04-19.

**Comment by activityworkshop** [comment] 2022-05-13 16:34
Thanks for the bug report - wow, that's embarrassing!  That scale bar bug should have been spotted earlier with the 21.2 testing.  I obviously overlooked the scale bar because it's separate from the map.  But you're completely correct, I've managed to reproduce the problem and the fix should be simple.  So it looks like there will be a version 21.3 after all!

About the tiny map text, yes this is discussed in issue 16 as you mention.  If the maps aren't scaled up (as they were in 21.1), then yes the text does look tiny, that's unavoidable if we want to avoid the pixellation.  The whole point of getting rid of the scaling with 21.2 was to make the maps look unscaled and crisp again.  So, without the scaling then I'd recommend you choose a map source with "extra-large" rendering, like the ones discussed and screenshotted in issue 16.

**Comment by lenlo** [comment] 2022-05-13 21:01
Thank you for your response and for all the good work with GpsPrune. It's one of the best apps I know for editing trails and I use it a lot! 👍

The increased sharpness is nice, but unfortunately, the map text is now so small on my MacBook Air Retina screen that I can no longer read it. Also, because I can't zoom in to the same level of magnification as in 21.1, it's really hard to edit the trail to the same level of detail as before as the points are simply too close to each other and the background detail is too small. 

What do you think about making high res maps like the ones on https://tile.osmand.net/hd/ the default when running on a device with a high res screen? They look great on my laptop, the only problem is that they become overblown when using an external monitor, so I now need to switch maps every time I switch between the laptop's own screen and the external one.

If this is too complicated or too much work, maybe the old scaling behavior could be made available as an option? I hate to say this, but the fuzzier maps under 21.1 work a lot better for me than the sharper (but smaller) standard maps under 21.2.

Let me know if I missed something... Thanks!

**Comment by activityworkshop** [comment] 2022-05-15 16:45
The scalebar bug is now fixed with 21.3 - thanks again for reporting this.

> What do you think about making high res maps like the ones on https://tile.osmand.net/hd/ the default when running on a device with a high res screen?

No, GpsPrune shouldn't choose your maps for you when you have selected one yourself - that's really up to you whether you want high-res maps or not and if so which one.  At most, GpsPrune _could_ show an information message which recommends that you configure and select a high-res source yourself, but unfortunately GpsPrune doesn't know for sure which sources are high-res and which ones aren't, so those kind of messages could be misleading.

For me, the best solution seems to be your idea of making the scaling behaviour an option - just a checkbox in the "display options" settings dialog.  By default it could use the 21.2 behaviour but if you uncheck the checkbox then it would go back to the earlier method.  That would be something for version 22.

Until then, you could either buy a external monitor which also has tiny pixels to match your laptop and use high-res maps on both, or just continue using GpsPrune 21.1 for now.

**Comment by activityworkshop** [comment] 2022-08-29 17:44
there's a new checkbox in v22 :)

**Closed by activityworkshop** 2022-08-29 17:44 UTC
